# Generated by Django 4.1.7 on 2023-03-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_verificationbadge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AlterField(
            model_name='verificationbadge',
            name='verifyImage',
            field=models.ImageField(blank=True, null=True, upload_to='verify'),
        ),
    ]
