# Generated by Django 4.1.7 on 2023-03-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationbadge',
            name='verifyImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
