# Generated by Django 4.1.7 on 2023-03-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_verificationbadge_verifyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationbadge',
            name='verifyImage',
        ),
    ]
