# Generated by Django 4.1.7 on 2023-04-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_verificationbadge_verifyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc', models.CharField(max_length=1000000)),
                ('price', models.CharField(max_length=10000)),
            ],
        ),
    ]
