# Generated by Django 4.1.7 on 2023-04-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ucpubg_delete_uc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UCPUBG',
        ),
    ]
